### ISSUE TITLE
Error on certain functions when having a NaN

### ISSUE THREAD

**Issue by anitsirc** [mrcsparker/kalc#11]
Hello :) 

I've experienced that some functions crashes when one of the arguments is a NaN (for instance 0/0). Initially I noticed it on `MIN` and `MAX` but then also found it in other places as well. 

Check the following
```ruby
references = { 
  a: "0", 
  b: "0", 
  c: "a/b", 
  d: "MAX(a,b,c)", 
  e: "MIN(a,b,c)", 
  f: "FLOOR(c)", 
  g: "ROUND(c)", 
  h: "SUM(a,b,c)" 
}
calc = Kalc::Runner.new
# Load references
references.each_pair { |k, v| calc.run("#{k} := #{v}") }

# Evaluate each reference
calc.run('a') # => 0.0
calc.run('b') # => 0.0
calc.run('c') # => NaN

calc.run('d')
RuntimeError: Argument Error. Function MAX was called with 3 parameters. It needs at least 1 parameters
from ~/.rvm/gems/ruby-2.4.2/gems/kalc-1.2.0/lib/kalc/ast.rb:252:in `rescue in eval'

calc.run('e')
RuntimeError: Argument Error. Function MIN was called with 3 parameters. It needs at least 1 parameters
from ~/.rvm/gems/ruby-2.4.2/gems/kalc-1.2.0/lib/kalc/ast.rb:252:in `rescue in eval'

calc.run('f')
FloatDomainError: Computation results to 'NaN'(Not a Number)
from ~/.rvm/gems/ruby-2.4.2/gems/kalc-1.2.0/lib/kalc/interpreter.rb:258:in `floor'

calc.run('g')
RuntimeError: Argument Error. Function ROUND was called with 1 parameters. It needs at least 2 parameters
from ~/.rvm/gems/ruby-2.4.2/gems/kalc-1.2.0/lib/kalc/ast.rb:252:in `rescue in eval'

calc.run('h') # => NaN
```

I can make a PR with a proposal for MIN and MAX on the lines of 
```ruby 
env.add_function(:MAX, lambda { |cxt, first, *args|
  evaluated_args = (args << first).map { |a| a.eval(cxt) }
  return BigDecimal.new("NaN") if evaluated_args.any? { |a| a.is_a?(BigDecimal) && a.nan? }
  evaluated_args.max
})
```

But I'm not sure if there's a better place to catch this in a more generic way instead of function by function.

**Comment by mrcsparker** [comment]
Issue fixed in latest release
